version: '3'
services:
  db:
    image: postgres
    env_file: ./etc/db/.env
    ports:
        - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: train
      POSTGRES_PASSWORD: 3fd5c2a0df1ce9dc01f0698adc57c72b
      POSTGRES_DB: train_dev

  api:
    build: .
    env_file: ./etc/api/.env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/train
    ports:
      - "3000:3000"
    depends_on:
      - db